# **Clasificación de salud fetal**

In [11]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split


In [12]:
dataset = pd.read_csv('fetal_health.csv')

In [13]:
columnas_X = [0, 2, 3, 4, 5, 6, 7, 9, 12, 13]
X = dataset.iloc[:, columnas_X]
y = dataset.iloc[:, -1]

sc = StandardScaler()
X_scaled = sc.fit_transform(X)

In [15]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
y_ = np.array(y)
y_ = encoder.fit_transform(y_.reshape(-1,1)).toarray()
print(y_)

[[0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [16]:
y = y_

In [20]:
num_componentes = [10, 9, 5, 3]
resultados = []

for n in num_componentes:
    pca = PCA(n_components=n)
    X_pca = pca.fit_transform(X_scaled)

    # Dividir los datos en conjuntos de entrenamiento y prueba
    X_train, X_test, y_train, y_test = train_test_split(X_pca, y, test_size=0.2, random_state=42)

    # Crear y entrenar el modelo de red neuronal
    model = tf.keras.models.Sequential()
    model.add(tf.keras.layers.Dense(units=10, activation='relu'))
    model.add(tf.keras.layers.Dense(units=6, activation='relu'))
    model.add(tf.keras.layers.Dense(units=6, activation='relu'))
    model.add(tf.keras.layers.Dense(units=3, activation='softmax'))
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    model.fit(X_train, y_train, epochs=10, batch_size=32)

    # Evaluar el modelo en el conjunto de prueba
    _, accuracy = model.evaluate(X_test, y_test)

    resultados.append(accuracy)


Epoch 1/10
54/54 [==============================] - 1s 2ms/step - loss: 1.1146 - accuracy: 0.5100
Epoch 2/10
54/54 [==============================] - 0s 2ms/step - loss: 0.8990 - accuracy: 0.7506
Epoch 3/10
54/54 [==============================] - 0s 2ms/step - loss: 0.7428 - accuracy: 0.7835
Epoch 4/10
54/54 [==============================] - 0s 2ms/step - loss: 0.6282 - accuracy: 0.7947
Epoch 5/10
54/54 [==============================] - 0s 2ms/step - loss: 0.5356 - accuracy: 0.8106
Epoch 6/10
54/54 [==============================] - 0s 2ms/step - loss: 0.4744 - accuracy: 0.8194
Epoch 7/10
54/54 [==============================] - 0s 2ms/step - loss: 0.4381 - accuracy: 0.8306
Epoch 8/10
54/54 [==============================] - 0s 2ms/step - loss: 0.4151 - accuracy: 0.8335
Epoch 9/10
54/54 [==============================] - 0s 2ms/step - loss: 0.3981 - accuracy: 0.8347
Epoch 10/10
14/14 [==============================] - 0s 2ms/step - loss: 0.4239 - accuracy: 0.8216
Epoch 1/10
54/54 [=

In [21]:
for i, n in enumerate(num_componentes):
    print(f"Número de componentes: {n}, Accuracy: {resultados[i]}")


Número de componentes: 10, Accuracy: 0.8215962648391724
Número de componentes: 9, Accuracy: 0.7957746386528015
Número de componentes: 5, Accuracy: 0.8615023493766785
Número de componentes: 3, Accuracy: 0.8544601202011108
